### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "qwer1234"
}


### Post
POST http://localhost:8080/api/v1/board/posts
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsInRva2VuX3R5cGUiOiJhY2Nlc3MiLCJqdGkiOiIzNTQ4NmVhZWQ4MjgiLCJpc3MiOiJodHRwczovL2FjY291bnRzLmJleW9uZC5jb20iLCJpYXQiOjE3NTc1Nzg0NTksImV4cCI6MTc1NzU3OTM1OX0.8Y-YZdycFLPrsr8TCVbPieYxrmJioqdSg6HPK6rW_vk
Content-Type: application/json

{
  "opinion": "Strong Sell",
  "content": "yyy",
  "stockId": 1004,
  "userId": 2
}

### GET Post Details
GET http://localhost:8080/api/v1/board/posts/8

### GET Post Lists
GET http://localhost:8080/api/v1/board/posts?stockId=1003